Repository darkflarengine/wjson, pull requests merged in 2022-07, with the labels that each got.

#2 feat: add `extends` option
  schema.json
  src/modules/parseConfig.ts
  src/type.d.ts
  test/custom.ts
  test/wrangler.json
Labels: feature

#4 feat: add yaml support
  package-lock.json
  package.json
  readme.md
  src/modules/parseConfig.ts
  test/wrangler.yml
Labels: feature

#6 feat: add basic error logging
  .changeset/curly-otters-return.md
  package-lock.json
  package.json
  src/bin/index.ts
  src/modules/generateConfig.ts
  src/modules/parseConfig.ts
Labels: feature

#17 refactor!: move env related config under `env` key
  .changeset/wet-fireants-visit.md
  schema.json
  src/modules/generateConfig.ts
  src/type.d.ts
  test/custom.ts
  test/wrangler.json
  test/wrangler.yml
Labels: enhancement

#26 feat: add support for `.jsonc` files
  .changeset/nice-rice-bow.md
  README.md
  package-lock.json
  package.json
  src/modules/parseConfig.ts
Labels: feature

#28 fix: spacing after `route` option in output file
  .changeset/neat-dodos-protect.md
  src/modules/generateConfig.ts
Labels: bug

#33 docs: add contact section to readme
  .changeset/thin-crabs-crash.md
  README.md
Labels: documentation
